version: 2.0

defaults: &defaults
  working_directory: ~/galgebra
  steps:
    - checkout
    - run:
        name: Install
        command: |
          sudo pip install -r test_requirements.txt
          sudo pip install -e .
          if [ -n "$PIP_EXTRA_INSTALLATION" ]; then
            # deliberately not quoted
            sudo pip install $PIP_EXTRA_INSTALLATION
          fi
          sudo pip check
    - run:
        name: Test
        command: |
          # we can't pass lists of arguments with spaces through environment
          # variables, so reassemble the list here
          PYTEST_ARGS=();

          PYTEST_ARGS+=(-n 2 --dist loadscope);;

          if [[ ! -z "$PYTEST_K_FILTER" ]]; then
            PYTEST_ARGS+=(-k "$PYTEST_K_FILTER");
          fi;

          mkdir -p test-reports/pytest
          pytest \
            --cov=galgebra \
            --nbval examples/ipython/ \
            test \
            --current-env \
            --sanitize-with test/.nbval_sanitize.cfg \
            --junitxml=test-reports/pytest/results.xml \
            "${PYTEST_ARGS[@]}"
    - run:
        name: Coverage
        when: on_success
        command: |
          sudo pip install codecov
          codecov
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports

jobs:
  "flake8":
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo pip install flake8 flake8_formatter_junit_xml
      - run:
          name: Lint
          command: |
            mkdir -p test-reports/flake8
            flake8 --format=junit-xml --output-file=test-reports/flake8/results.xml
      - store_test_results:
          path: test-reports

    docker:
      - image: circleci/python:3.8

  # symengine does not seem to install correctly with Python 3.8 yet
  "python-3.7-symengine":
    <<: *defaults
    environment:
      PIP_EXTRA_INSTALLATION: numpy symengine==0.5.0
      USE_SYMENGINE: 1
    docker:
      - image: circleci/python:3.7
  # sympy 1.4 does not claim to support Python 3.8
  "python-3.7-sympy-1.4":
    <<: *defaults
    environment:
      PIP_EXTRA_INSTALLATION: sympy==1.4
    docker:
      - image: circleci/python:3.7

  "python-3.8-sympy-master":
    <<: *defaults
    environment:
      # use the archive url to prevent full git clone
      PIP_EXTRA_INSTALLATION: https://github.com/sympy/sympy/archive/master.zip
    docker:
      - image: circleci/python:3.8

  # make sure to keep setup.py in sync with these
  "python-3.9":
    <<: *defaults
    docker:
      - image: circleci/python:3.9
  "python-3.8":
    <<: *defaults
    docker:
      - image: circleci/python:3.8
  "python-3.7":
    <<: *defaults
    docker:
      - image: circleci/python:3.7
  "python-3.6":
    <<: *defaults
    docker:
      - image: circleci/python:3.6

  "publish":
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Upload to PyPi
          command: |
            ./circle-build-package

workflows:
  version: 2
  build:
    jobs:
      - "flake8":
          filters:
            tags:
              only: /^v.*$/

      - "python-3.9":
          filters:
            tags:
              only: /^v.*$/
          requires: ["flake8"]
      - "python-3.8":
          requires: ["flake8"]
      - "python-3.7":
          requires: ["flake8"]
      - "python-3.6":
          requires: ["flake8"]
      - "python-3.7-symengine":
          requires: ["flake8"]
      - "python-3.7-sympy-1.4":
          requires: ["flake8"]
      - "python-3.8-sympy-master":
          requires: ["flake8"]

      - publish:
          requires:
            - "python-3.9"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
